#!/bin/sh
#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, symlink it from ".git/hooks/pre-commit".


# Runs gofmt on the code and stops commit if files were affected.
# 


if (gofmt -w -l */*.go */*/*.go | grep \.go); then exit 1; fi;
go test

(cd examples && make)
